### ISSUE TITLE
Error: ('dict_items' object has no attribute 'sort') when attempting to export xls

### ISSUE THREAD

**Issue by bjornpoort** [saxix/django-adminactions#82]
![schermafbeelding 2015-12-08 om 17 11 35](https://cloud.githubusercontent.com/assets/14273799/11660682/91bd7952-9dce-11e5-92f8-23349eb26ec8.png)

Using python 3.5 and django 1.8.7. It worked before with python 3.5, so not really sure whether this is a compatibility issue? Anyone has an idea why this error is raised?

**Comment by saxix** [comment]
cannot reproduce the error. I added a test for it but it passes. can you share the versions of the [dependencies](https://github.com/saxix/django-adminactions/blob/develop/src/adminactions/requirements/install.any.pip) ?

**Comment by bjornpoort** [comment]
six==1.10.0
pytz==2015.7
unicodecsv==0.14.1
xlrd==0.9.4
xlwt-future==0.8.0

**Comment by haren** [comment]
@saxix @bjornpoort  I have identified the issue. 

This is the responsible line where the code fails:
https://github.com/saxix/django-adminactions/blob/develop/src/adminactions/api.py#L360

It's therefore in an external, `xlwt` library. The following lines perform a `.sort()` operation, but what is passed from `export_as_xls` is a `dict_items` object. What solves the issue is simply casting the `dict_items` object to `list`.

https://github.com/python-excel/xlwt/blob/master/xlwt/Style.py#L196
https://github.com/python-excel/xlwt/blob/master/xlwt/Style.py#L208
https://github.com/python-excel/xlwt/blob/master/xlwt/Style.py#L221

@saxix do you believe it's a patch on your or their site? Let me know how I can help further.

**Comment by saxix** [comment]
great catch @haren. If you can provide a PR I'll be happy to merge. I plan to work on aa this week, trying to close some other ticket.

**Comment by bjornpoort** [comment]
Hi saxix, any update on this issue? Haren's fix worked, but only for local development. kind regards, bjorn

**Comment by saxix** [comment]
woops, sorry to say that but I totally forgot this issue. The links seems to point to wrong lines, and cannot recall the problem. grep for '.sort' in the code do not give me any result. Not sure if the issue has been resolved and only packaging is required.
